language: python
sudo: false
python: 2.7
env:
  - TOX_ENV=py27-1.7
  - TOX_ENV=py27-1.8
  - TOX_ENV=py33-1.7
  - TOX_ENV=py33-1.8
  - TOX_ENV=py34-1.7
  - TOX_ENV=py34-1.8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
