language: python
sudo: false
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
env:
  - DJANGO_VERSION="1.7"
  - DJANGO_VERSION="1.8"
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION="1.7"
install:
  - pip install "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.999" jinja2
script:
  - python run_tests.py
